### ISSUE TITLE
Move to poetry and masonry for deployment?

### ISSUE THREAD

**Issue by baseplate-admin** [hitblast/avro.py#28]
Hi,

It seems you are using [setuptools](https://github.com/hitblast/avro.py/blob/f535544fdd83577c0864b681ea092321b13e374b/setup.py) to install the application. But the entire python ecosystem is moving towards `pyproject.toml` format.

 Check this [reddit](https://www.reddit.com/r/learnpython/comments/xjyz13/why_use_poetry_instead_of_requirementstxt_files/) thread for why people chose poetry over setuptools.
 
 Thanks in advance

**Comment by hitblast** [comment]
@baseplate-admin Thanks for this update! I really appreciate it and will look into it as soon as possible.

**Comment by hitblast** [comment]
https://github.com/hitblast/avro.py/compare/main...migrate-poetry

@baseplate-admin Hey, I've made the basic changes for migrating the project to Poetry. I'd also like to talk about if we should keep the `setup.py` file for legacy purposes or not. Feel free to check when you're free. Thanks!

**Comment by baseplate-admin** [comment]
Could you please open a pull request? i will do verification there.

Karon eibhabe verification korte gele onek onek pera hobe :)

**Comment by hitblast** [comment]
@baseplate-admin accha thikache :)

**Comment by baseplate-admin** [comment]
jodi ei line e jete chaw,

add this to `dependabot`:
https://github.com/baseplate-admin/django-ltree-2/blob/55584e9075cad1c9f4a0141523048630a52a4121/.github/dependabot.yml#L13-L17

**Comment by baseplate-admin** [comment]
![image](https://github.com/hitblast/avro.py/assets/61817579/ddf99f07-3f2f-4345-8a3b-83802a830d60)


You should always commit lock file to allow dependabot to update deps

**Comment by baseplate-admin** [comment]
ideally you should include pytest in test deps

https://github.com/baseplate-admin/django-ltree-2/blob/55584e9075cad1c9f4a0141523048630a52a4121/pyproject.toml#L33-L35

**Comment by hitblast** [comment]
> tumi chaile https://github.com/baseplate-admin/django-ltree-2/blob/55584e9075cad1c9f4a0141523048630a52a4121/.github/workflows/publish.yml ei type kisu use krte paro, publishing onek easy hobe taile

Yeah ekta workflow file pore add kore dicchi dw

**Comment by hitblast** [comment]
@baseplate-admin okay read all of your comments, attempting to adjust it
