### ISSUE TITLE
This code can be optimized using list comprehension

### ISSUE THREAD

**Issue by baseplate-admin** [hitblast/avro.py#31]
https://github.com/hitblast/avro.py/blob/f535544fdd83577c0864b681ea092321b13e374b/avro/utils/count.py#L9-L34

Check this :
* https://www.linkedin.com/pulse/loop-vs-list-comprehension-map-function-akhilesh-singh

**Comment by hitblast** [comment]
I've already been using list comprehension in other parts of the code, but thanks :D really appreciate it.

**Comment by baseplate-admin** [comment]
This can be even better if we use built in functions. Let me see if i find something

**Comment by hitblast** [comment]
@baseplate-admin Could you please have a look at the pull request mentioned above?
