### ISSUE TITLE
Change contributing section in README.md?

### ISSUE THREAD

**Issue by baseplate-admin** [hitblast/avro.py#37]
Hi the instructions in README.md seems a bit too complex.

It should be :

```
poetry install
poetry run pytest .
```

These are what i did to test locally

**Comment by baseplate-admin** [comment]
Just make sure to install poetry

**Comment by hitblast** [comment]
@baseplate-admin Alright. I'll have a look into this.

**Comment by hitblast** [comment]
Update: Fixed with the https://github.com/hitblast/avro.py/commit/233edfdc60374d62c5ba97498f92a4a5f9319747 commit.

**Comment by baseplate-admin** [comment]
```
pip install -U pip setuptools
```

Is this required?

Also poetry should not be installed with pip, but pipx.

The reason is it gives isolated environment.

**Comment by hitblast** [comment]
@baseplate-admin I was planning to recreate a pipx environment on my machine but since avro.py doesn't really rely on dependencies outside of pip, I had kept poetry installation inside pip as-is.

Will reconsider it.

**Comment by baseplate-admin** [comment]
poetry is a development dependency, it is not a single dependency.

Consider it like this.

Poetry python er motoi machine e installed thake, eita vscode er moto consider kora jete pare :)

**Comment by hitblast** [comment]
@baseplate-admin Bujhechi beparta, don't worry. ;)

**Comment by hitblast** [comment]
@baseplate-admin Apparently not using the `--all-extras` flag removes the CLI dependencies as well, so I guess I'll keep it for the developer notes.
