### ISSUE TITLE
Try to add an actual documentation?

### ISSUE THREAD

**Issue by baseplate-admin** [hitblast/avro.py#38]
The next step for this project is to add actual documentation explaining how things work.

There are 2 (actually 3) paths to take:
1. sphinx
2. mkdocs
3. bring-your-own-documentation-framework

Personally i use sphinx for everything. It's very easy to setup.

**Comment by hitblast** [comment]
Sphinx is actually great in my opinion, have used it professionally for some of my projects before, but didn't think of adding it to avro.py. Could be a nice addition.

**Comment by baseplate-admin** [comment]
The only problem i have with sphinx is it's lackluster theme.

Like `material for mkdocs` chokhe lagse :|

**Comment by hitblast** [comment]
> The only problem i have with sphinx is it's lackluster theme.
> 
> Like `material for mkdocs` chokhe lagse :|

I'll have a look.

**Comment by baseplate-admin** [comment]
https://squidfunk.github.io/mkdocs-material/

**Comment by hitblast** [comment]
@baseplate-admin I've also found a Rust-based solution for creating the documentation, which apparently uses the `mdbook` package. Here's a workflow from one of my other projects: https://github.com/IgKniteDev/docs/blob/main/.github/workflows/deploy.yml

**Comment by baseplate-admin** [comment]
> I've also found a Rust-based solution for creating the documentation

To be honest, python docstrings are maybe not supported in `mdbook`. 

Take a look at this [documentation](https://modern-colorthief.readthedocs.io/en/latest/api.html). Coding something like this as trivial as [this](https://github.com/baseplate-admin/modern_colorthief/blob/6326be465055ddcdd25f4a488926a547d48ecc99/docs/api.md). 

Now tumi eita `mdbook` diyew krte paro, but it's time consuming and in my honest opinion not worth it.

Sphinx/Mkdocs also has a lot of themes.
Notable ones:
* [`shibuya`](https://shibuya.lepture.com/) [ sphinx ]
* [`material-for-mkdocs`](https://github.com/squidfunk/mkdocs-material/) [ mkdocs ]

And you also get free hosting at https://readthedocs.io .
