### ISSUE TITLE
✨ Full async rewrite?

### ISSUE THREAD

**Issue by hitblast** [hitblast/avro.py#63]
Since the project is hugely I/O bound, I think it'd be good to add `async`/`await` to the structure of it. If it's considered, I'd like to know about the different considerable approaches for doing so, whilst modifying the current codebase in a different branch.

Mentions: @furtidev @baseplate-admin @TanimSk

**Comment by baseplate-admin** [comment]
I personally dont think, it's worth it as you are already using `_concurrency_helper` that executes the code in a `ThreadPool`.

**Comment by hitblast** [comment]
@baseplate-admin True. I guess I'll leave this addition for now.

**Comment by baseplate-admin** [comment]
But, there are alternatives like [trio nursery](https://trio.readthedocs.io/en/stable/tutorial.html), that will make it easy to do multiprocessing.

But since python 3.13 has a JIT, i dont think adding threading is even worth it.
